### ISSUE TITLE
Reset pin and delay provider

### ISSUE THREAD

**Issue by therealprof** [EdgewaterDevelopment/rust-ssd1306#1]
So I was trying to try out the driver and was stumbling across the hard assignment of a reset pin and the forced use of a Delay implementation to drive it. This seems quite a bit limiting if the reset pin is not hooked up and/or the implementation doesn't provide a delay provider.

Would you accept a PR to make `reset()` an independent method from `init()` and change the signatures of `new()`, `init()` and `reset()` so only the latter uses the reset pin and the delay for a brief moment of time?

**Comment by wose** [comment]
I agree, all SSD1306 modules I own (some breakout boards and the one in the [ts100)](https://github.com/wose/ts100) have their RST pin tied to ground.

**Comment by scowcron** [comment]
Couple of thoughts. First, yes, I agree on separating `reset()` and `init()`. I'll go ahead and do that.

As to what to do with the reset pin, I'd be happy to hear ideas or see PRs as to what you'd like to see happen there. My first thought was to turn `Ssd1306.rst` into an `Option<RST>`, but that falls apart when you try to construct the object - the compiler can't infer the type, so you have to give it some arbitrary `OputputPin` as a type parameter when you construct the thing - it's more pain than it's worth.

The other option I can think of would be to take an `OutputPin` on the `reset()` method along with the delay, which I think is what was suggested here. I like the idea of taking ownership of that pin if it's in use, but this might be the better option.

**Comment by therealprof** [comment]
> The other option I can think of would be to take an OutputPin on the reset() method along with the delay, which I think is what was suggested here. I like the idea of taking ownership of that pin if it's in use, but this might be the better option.

Yes, that was the suggestion.

**Comment by scowcron** [comment]
fixed with 6d85842d3d2f09238a11789fcb6b25c2c470166d

**Comment by therealprof** [comment]
Hm, why not just borrow the pin and delay provider instead of moving in and out?

**Comment by scowcron** [comment]
sure, how's this look? ca0aae66cac0a489aba8e8ab5f43b77ab6ee63dc

**Comment by therealprof** [comment]
👍
